applications/empleados/urls.py
from django.urls import path
#from django.conf.urls.static import static

#Importando ruta del la vista(controlador) a las rutas
from . import views

app_name = "employee_app"

urlpatterns = [
    path('employees/', views.ListEmployees.as_view(), name='empleados'),
    #ruta con parametros
    path('employees-by-area/<short_name>', views.ListByArea.as_view(), name='employeesByArea'),

    path('search-employee', views.ListByKword.as_view()),
    path('skills-employee', views.ListHabilidades.as_view()),
    path('details-employee/<pk>', views.EmpleadoDetailView.as_view(), name='show'),
    path('create-employee', views.CreateEmpleado.as_view(), name='store'),
    path('update-employee/<pk>', views.UpdateEmpleado.as_view(),  name='update'),
    path('delete-employee/<pk>', views.deleteEmpleado.as_view(), name='destroy'),
    path('success', views.SuccessView.as_view(), name='correcto'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
#archivo de configuracion de url de imagenes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Importando rutas del archivo de rutas de una applicacion
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.empleados.urls')),
    re_path('', include('applications.departamento.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleados/models.py
from django.db import models

#importando modelo para relacionar
from  applications.departamento.models import Departamento

#Utilizando aplicacion de terceros checkditor
from ckeditor.fields import RichTextField

class Habilidad(models.Model):
    habilidad = models.CharField('habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidades'
        verbose_name_plural =  'Habilidad de empleado'

    def __str__( self ):
        return str(self.id) + '-' + self.habilidad


class Empleado(models.Model):

    JOB_CHOISES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro'),
    )

    first_name = models.CharField('first_name', max_length=50)
    last_name = models.CharField('last_name', max_length=50)
    full_name = models.CharField('full_name', max_length=120, blank=True)
    job = models.CharField('job', max_length=50, choices=JOB_CHOISES)  #tipo enum
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='empleado', blank=True, null=True)
    Habilidades = models.ManyToManyField(Habilidad)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Employee'
        verbose_name_plural =  'empleados de la empresa'
        ordering = ['-first_name'] #el guión indica que se ordenara en orden inverso

    def __str__( self ):
        return str(self.id) + '-' + self.first_name + ' ' + self.last_name

applications/empleados/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'full_name',
            'job',
            'departamento',
            'image',
            'Habilidades',
            'hoja_vida',
        )
        widgets = {
            'Habilidades' : forms.CheckboxSelectMultiple()
        }

applications/empleados/views.py
from typing import Any
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
from .models import Empleado
from .forms import EmpleadoForm

class ListEmployees(ListView):
    #estos son Attributes
    template_name = 'empleados/index.html'
    #model = Empleado
    context_object_name = 'employees'
    #si no mando un context_object_name puedo acceder a los datos del modelo a de una variable generada por default llamada object_list

    #paginacion
    paginate_by = 5
    ordering = 'first_name'

    def get_queryset(self):  #funcion que realiza la busqueda de empleados por el campo fullname
        kword = self.request.GET.get('kword','')
        employees = Empleado.objects.filter(
            full_name__icontains = kword #el icontains busca rl texto excrito en el input dentro del fullname
        )
        return employees

class ListByArea(ListView):
    template_name = 'empleados/list_by_area.html'
    #Realizar busqueda de registros aplicando filtros

    def get_queryset(self):
        employees = Empleado.objects.filter(
            departamento__short_name = self.kwargs['short_name']
        )
        return employees

#Busqueda desde formulario
class ListByKword(ListView):
    template_name = 'empleados/by_kword.html'
    context_object_name = 'employees'

    def get_queryset(self):
        kword = self.request.GET.get('kword','')
        employees = Empleado.objects.filter(
            first_name = kword
        )
        return employees
    
class ListHabilidades(ListView):
    template_name = 'empleados/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=1)
        #recuperando datos una relacion mucho a muchos en este casa de la tabla habilidad nota el foreingkey es Habilidades
        print(empleado.Habilidades.all())
        return empleado.Habilidades.all()
    

#Esto es como la función "show" en laravel, recupera la información de un registro con un id dado
class EmpleadoDetailView(DetailView):
    template_name = "empleados/show.html"
    model = Empleado
    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context



class SuccessView(TemplateView):
    template_name = "empleados/success.html"


class CreateEmpleado(CreateView):
    model = Empleado
    template_name = "empleados/create.html"
    #agregar campos por separado en la variable "form" que almacena todos los campos
    #fields = ['first_name', 'last_name',  'image', 'job', 'departamento','Habilidades',]

    #Se esta trabajando con formulario personalizado
    form_class = EmpleadoForm

    #agregar todos los campos
    #fields = ('__all__')

    #success_url = 'employees' #poner . regresa a la misma pagina una ves guardado esto se puede pero no es una buena practrica
    success_url = reverse_lazy('employee_app:empleados') #se utiliza la funcion reverse_lazy de django  y el nombre de url asignado

    #metodo para interseptar el guardado y validar campos
    #la variable form almacena lo enviado desde el formulario
    def form_valid(self, form):
        empleado = form.save(commit=False) #se crea una instancia de lo que se guardara en bd
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(CreateEmpleado, self).form_valid(form)
    

class UpdateEmpleado(UpdateView):
    model = Empleado
    template_name = "empleados/edit.html"
    fields = ['first_name', 'last_name', 'job', 'image','departamento','Habilidades']
    success_url = reverse_lazy('employee_app:empleados')

    # realizar un procesi previo al actualizado 
    #el post se ejecura antes que el form_valid no importa el orden en que se ponga
    #Aqui todavia no se validan los datos
    def post(self, request, *args, **kwargs):
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)
        
    #esto se ejecuta una vez que se valida que los datos sean correctos 
    def form_valid(self, form):
        empleado = form.save(commit=False) #se crea una instancia de lo que se guardara en bd
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(UpdateEmpleado, self).form_valid(form)


class deleteEmpleado(DeleteView):
    model = Empleado
    template_name = "empleados/delete.html"
    success_url = reverse_lazy('employee_app:empleados')

    def delete(self, request, *args,  **kwargs) :
        self.object = self.get_object()
        print( self.object)      
        self.object.delete()
        return super().delete(request, *args, **kwargs)

templates/empleados/by_kword.html
<h1>Search Employee</h1>
<form method="GET">
  {% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="type name of employee">
    <button type="submit">Send</button>
</form>

<ul>
    {% for employee in employees %}
    <li>{{ employee.first_name }}</li>
    {% endfor %}        
</ul>

templates/empleados/create.html
{% extends 'layout/layout.html' %}
    {% block 'title' %} Listado de Empleados {% endblock 'title' %}

    {% block 'body' %}

    <div class="grid-container">
        <h1>Create</h1>
        <!-- Esta variable crea un formulario basado en los campos que establecimos en la variable fields del view -->
        <!-- as_p alinea los campos de manera vertical -->

        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form.as_p }}
            <button class="button success" type="submit">Save</button>
        </form>
    </div>
    {% endblock 'body' %}

templates/empleados/delete.html
{% extends 'layout/layout.html' %}
    {% block 'title' %} DeleteEmpleados {% endblock 'title' %}

    {% block 'body' %}
       <div class="grid-container" style="margin-top: 10px;">
        <form method="POST">  
            {% csrf_token %}   
            <div class="callout alert" data-closable="slide-out-right">
                <h5>Delete employee.</h5>
                <p>Are you sure you want to delete to {{object.full_name }}? </p>
                <button class="close-button" aria-label="Dismiss alert" type="submit" data-close>
                <span aria-hidden="true">delete</span>
                </button>
            </div>
        </form>
       </div>

    {% endblock 'body' %}

templates/empleados/edit.html
{% extends 'layout/layout.html' %}
    {% block 'title' %} Listado de Empleados {% endblock 'title' %}

    {% block 'body' %}

    <div class="grid-container">
      <h1>Update</h1>

      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
          {{ form.as_p }}
          <button class="button success" type="submit">Save</button>
      </form>
    </div>

    {% endblock 'body' %}

templates/empleados/habilidades.html
<h1>Habilidades</h1>

<ul>
    {% for habilidad in habilidades %}
    <li>{{ habilidad }}</li>
    {% endfor %}        
</ul>

templates/empleados/index.html
{% extends 'layout/layout.html' %}
    {% block 'title' %} Listado de Empleados {% endblock 'title' %}

    {% block 'body' %}
    <div class="grid-container">
      <div class="grid-x">
        <h1 class="cell">Listado de empleados</h1>
      </div>
      
       <form method="GET" class="cell grid-x">
        {% csrf_token %}
            <div class="cell large-7">
                <input type="text" name="kword" placeholder="type name of employee"/> 
            </div>
            <div class="cell large-2" style="margin-left: 10px;">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>

        <div>
          <a class="button primary" href="{% url 'employee_app:store' %}">Nuevo Empleado</a>
        </div>
   

      <div class="cell">
        <table class="hover">
          <thead>
             <tr>
                <th>Id</th>
                <th>Firstname</th>
                <th>Lastname</th>                
                <th>Departamento</th>
                <th></th>
             </tr>
          </thead>
          <tbody>
            {% for employee in employees %}
            <tr>
                <td>{{ employee.id }}</td>
                <td>{{ employee.first_name }}</td>
                <td>{{ employee.last_name }}</td>
                <td>{{ employee.departamento.name }}</td>
                <td>
                    <a class="button primary" href="{% url 'employee_app:show' employee.id %}">ver</a>
                    <a class="button secondary" href="{% url 'employee_app:update' employee.id %}">editar</a>
                    <a class="button warning" href="{% url 'employee_app:destroy' employee.id %}">eliminar</a>
                </td>
            </tr>
            {% endfor %}      
          </tbody>
        </table>
      </div>
      <div class="cell">
        {% if is_paginated %}
         <nav aria-label="Pagination">
           <ul class="pagination text-center">
            
            {% if page_obj.has_previous  %}
                <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Previous</a></li>
            {% endif %}
                
            
            {% for page in paginator.page_range  %}
                {% if page == page_obj.number  %} 
                  <li class="current"><span class="show-for-sr">You're on page</span>{{ page }}</li>
                {% else %}
                  <li><a href="?page={{page}}">{{ page }}</a></li>
                {% endif %}  
            {% endfor %}
                
           
            {% if page_obj.has_next  %}
             <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next</a></li>
            {% endif %}
             
           </ul>
         </nav>
        {% endif %}
            
      </div>
    </div>

    {% endblock 'body' %}

templates/empleados/list_by_area.html
{% extends 'layout/layout.html' %}
    {% block 'title' %} Departamentos {% endblock 'title' %}

    {% block 'body' %}

        <h1>Lista de empleados por departamento</h1>
        
        <div class="grid-x">
            <div class="cell">
                <table class="hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Firstname</th>
                        <th>Lastname</th>                
                        <th>Departamento</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for employee in object_list %}
                    <tr>
                        <td>{{ employee.id }}</td>
                        <td>{{ employee.first_name }}</td>
                        <td>{{ employee.last_name }}</td>
                        <td>{{ employee.departamento.name }}</td>
                    </tr>
                    {% endfor %}      
                </tbody>
                </table>
            </div>
        </div>

    {% endblock 'body' %}

templates/empleados/show.html
{% extends 'layout/layout.html' %}
    {% block 'title' %} Listado de Empleados {% endblock 'title' %}

    {% block 'body' %}
        <div class="grid-container">

            <div class="card" style="width: 500px; margin-top: 20px;">
                <div class="card-divider">
                      <!-- Se esta mostrando el registro encontrado a traves del nombre del modelo en minisculas -->
                      {{ empleado }}
                   
                </div>
                
                {% if empleado.image %}
                    <img src="{{ empleado.image.url }}" alt="">
                {% else %}
                    <img src="https://llerena.org/wp-content/uploads/2017/11/imagen-no-disponible.jpg" alt="">
                {% endif %}
                    
                <div class="card-section">
                    
                    <h1>{{ titulo }}</h1>

                    <h6>{{ empleado.first_name }} {{ empleado.last_name }}</h6>
                    <h6>{{ empleado.get_job_display }}</h6>  <!-- nos recupera el valor de un diccionario(arreglo) -->
                    <h6>{{ empleado.departamento.name }}</h6>

                    <h6>{{ empleado.hoja_vida }}</h6>
                    <p><span class="label">habilidades</span></p>
                    <ul class="vertical menu">
                        
                        {% for h in  empleado.Habilidades.all %} <!-- recuperando de arreglo de  habilidades  -->
                            <li>{{ h.habilidad }}</li>                            
                        {% endfor %}
                            
                    </ul>
                </div>
              </div>
        </div>
    {% endblock 'body' %}

templates/empleados/success.html
<h1>Success</h1>