applications/departamento/urls.py
from django.urls import path
from . import views

app_name = "department_app"

urlpatterns = [
    path('index-department', views.ListDepartments.as_view(), name='departments'),
    path('create-department', views.CreateDepartment.as_view(), name='store')
]

applications/empleados/urls.py
from django.urls import path
#from django.conf.urls.static import static

#Importando ruta del la vista(controlador) a las rutas
from . import views

app_name = "employee_app"

urlpatterns = [
    path('employees/', views.ListEmployees.as_view(), name='empleados'),
    #ruta con parametros
    path('employees-by-area/<short_name>', views.ListByArea.as_view(), name='employeesByArea'),

    path('search-employee', views.ListByKword.as_view()),
    path('skills-employee', views.ListHabilidades.as_view()),
    path('details-employee/<pk>', views.EmpleadoDetailView.as_view(), name='show'),
    path('create-employee', views.CreateEmpleado.as_view(), name='store'),
    path('update-employee/<pk>', views.UpdateEmpleado.as_view(),  name='update'),
    path('delete-employee/<pk>', views.deleteEmpleado.as_view(), name='destroy'),
    path('success', views.SuccessView.as_view(), name='correcto'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
#archivo de configuracion de url de imagenes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Importando rutas del archivo de rutas de una applicacion
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.empleados.urls')),
    re_path('', include('applications.departamento.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('nombre', max_length=50)
    short_name = models.CharField('nombre_corto', max_length=20, blank=True, null=True, unique=True)
    status = models.BooleanField('status', default=True)
    
    #Esta clase permite definir los nombres con los que aparecera la tabla en el administrador de django
    class Meta:
        verbose_name = 'Deparment'
        verbose_name_plural =  'Áreas de la empresa'
        ordering = ['-name'] #el guión indica que se ordenara en orden inverso
        unique_together =  ('name', 'short_name') #evita que se registren nombres duplicados o convinaciones de nombre de campo de departamento

    def __str__( self ):
        return str(self.id) + '-' + self.name + '-' + self.short_name

applications/departamento/forms.py
from django import forms

class CreateDeparment(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=50)

applications/departamento/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from .forms import CreateDeparment

from applications.empleados.models import Empleado
from .models import Departamento


class ListDepartments(ListView):
    template_name = "departamentos/index.html"
    context_object_name = 'departamentos'
    paginate_by =  5

    def get_queryset(self):
        kword = self.request.GET.get('kword', '')
        departamentos = Departamento.objects.filter(
            name__icontains = kword
        )
        return departamentos


# Create your views here.
class CreateDepartment(FormView):
    template_name = 'departamentos/create.html'
    form_class = CreateDeparment
    success_url = '.'

    def form_valid(self, form):
        #instancia del modelo departamanto
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            short_name = form.cleaned_data['shortname']
        )

        depa.save()
        #Recuperando datos que vienen del formulario
        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']

        #guardando empleado usando el modelo Empleados
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellidos,
            job = 3,
            departamento = depa
        )
        return super(CreateDepartment, self).form_valid(form)

templates/departamentos/create.html
{% extends 'layout/layout.html' %}
    {% block 'title' %} Registrar departamento {% endblock 'title' %}

    {% block 'body' %}

    <div class="grid-container">
        <h1>Create departamentos</h1>

        <form method="POST">
        {% csrf_token %}
            <h3>Datos Empleado</h3>
                <div>
                    {{ form.nombre }}
                </div>
                <div>
                    {{ form.apellidos  }}
                </div>

            <h3>Datos del departamento </h3>
                <div>
                    {{ form.departamento }}
                </div>
                <div>
                    {{ form.shortname  }}
                </div>

            <button class="button success" type="submit">Save</button>
        </form>
    </div>

    {% endblock 'body' %}

templates/departamentos/index.html
{% extends 'layout/layout.html' %}
    {% block 'title' %} Departamentos {% endblock 'title' %}

    {% block 'body' %}
    <div class="grid-container">
        <div class="grid-x">
          <h1 class="cell">Listado de departamentos</h1>
        </div>

        <form method="GET" class="cell grid-x">
            <div class="cell large-7">
                <input type="text" name="kword" placeholder="type name of department"/>
            </div>
            <div class="cell large-2" style="margin-left: 10px;">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>

        <div>
          <a class="button primary" href="{% url 'department_app:store' %}">Registrar Departamento</a>
        </div>

        <div class="cell">
            <table class="hover">
              <thead>
                 <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Nombre corto</th>     
                    <th></th>     
                 </tr>
              </thead>
              <tbody>
                {% for department in departamentos %}
                <tr>
                    <td>{{ department.id }}</td>
                    <td>{{ department.name }}</td>
                    <td>{{ department.short_name }}</td>
                    <td>
                      <a class="button warning" href="{% url 'employee_app:employeesByArea' department.short_name %}">ver</a>
                    </td>
                </tr>
                {% endfor %}      
              </tbody>
            </table>
          </div>

          <div class="cell">
            {% if is_paginated %}
             <nav aria-label="Pagination">
               <ul class="pagination text-center">
                
                {% if page_obj.has_previous  %}
                    <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                {% endif %}
                    
                
                {% for page in paginator.page_range  %}
                    {% if page == page_obj.number  %} 
                      <li class="current"><span class="show-for-sr">You're on page</span>{{ page }}</li>
                    {% else %}
                      <li><a href="?page={{page}}">{{ page }}</a></li>
                    {% endif %}  
                {% endfor %}
                    
               
                {% if page_obj.has_next  %}
                 <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Next</a></li>
                {% endif %}
                 
               </ul>
             </nav>
            {% endif %}
                
          </div>
    </div>
    {% endblock 'body' %}