applications/departamento/urls.py
from django.urls import path
from . import views

app_name = "department_app"

urlpatterns = [
    path('index-department', views.ListDepartments.as_view(), name='departments'),
    path('create-department', views.CreateDepartment.as_view(), name='store')
]

applications/empleados/urls.py
from django.urls import path
#from django.conf.urls.static import static

#Importando ruta del la vista(controlador) a las rutas
from . import views

app_name = "employee_app"

urlpatterns = [
    path('employees/', views.ListEmployees.as_view(), name='empleados'),
    #ruta con parametros
    path('employees-by-area/<short_name>', views.ListByArea.as_view(), name='employeesByArea'),

    path('search-employee', views.ListByKword.as_view()),
    path('skills-employee', views.ListHabilidades.as_view()),
    path('details-employee/<pk>', views.EmpleadoDetailView.as_view(), name='show'),
    path('create-employee', views.CreateEmpleado.as_view(), name='store'),
    path('update-employee/<pk>', views.UpdateEmpleado.as_view(),  name='update'),
    path('delete-employee/<pk>', views.deleteEmpleado.as_view(), name='destroy'),
    path('success', views.SuccessView.as_view(), name='correcto'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
#archivo de configuracion de url de imagenes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Importando rutas del archivo de rutas de una applicacion
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.empleados.urls')),
    re_path('', include('applications.departamento.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout/caroussel.html
{% load static %} 
<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
    <div class="orbit-wrapper">
      <div class="orbit-controls">
        <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
        <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
      </div>
      <ul class="orbit-container">
        <li class="is-active orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'images/lego.jpg'%}" alt="Space">
            <figcaption class="orbit-caption">Space, the final frontier.</figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'images/home-office.jpg'%}" alt="Space">
            <figcaption class="orbit-caption">Lets Rocket!</figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'images/job.jpg'%}" alt="Space">
            <figcaption class="orbit-caption">Encapsulating</figcaption>
          </figure>
        </li>
      </ul>
    </div>
    <nav class="orbit-bullets">
      <button class="is-active" data-slide="0">
        <span class="show-for-sr">First slide details.</span>
        <span class="show-for-sr" data-slide-active-label>Current Slide</span>
      </button>
      <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
      <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
      <button data-slide="3"><span class="show-for-sr">Fourth slide details.</span></button>
    </nav>
  </div>

templates/layout/footer.html
<footer>
    <div class="grid-x grid-padding-x">
     <p class="cell">pie de pagina</p>
    </div>
 </footer>

templates/layout/header.html
<header>
  <div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li><a href="/">Inicio</a></li>
        <li><a href="{% url 'employee_app:empleados' %}">Empleados</a></li>
        <li><a href="{% url 'department_app:departments' %}">Departamentos</a></li>
        <li><a href="/admin">Administrar</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar..."></li>
        <li><button type="button" class="button">Search</button></li>
      </ul>
    </div>
  </div>
</header>

templates/layout/layout.html
{% load static %} <!-- Esto carga los archivos estaticos "css, images, js"-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static '/css/foundation.min.css' %}">
        <link rel="stylesheet" href="{% static '/css/app.css' %}">
        <title>
            {% block 'title' %}
            {% endblock 'title' %}
        </title>
    </head>
<body>
    {% include 'layout/header.html'%}

    {% block 'body' %}
    {% endblock 'body' %}

    {% include 'layout/footer.html'%}    
    
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>